version: '3'
 
services:
  # kamailio
  kamailio:
    build: 
      context: ./kamailio
      args:
        - SIP_DOMAIN=${KAMAILIO_SIP_DOMAIN}
        - DBRWUSER=${KAMAILIO_DBRWUSER}
        - DBRWPW=${KAMAILIO_DBRWPW}
        - DBROUSER=${KAMAILIO_DBROUSER}
        - DBROPW=${KAMAILIO_DBROPW}
        - DBROOTPW=${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "5060:5060"

  # mysql
  mysql:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33060:3306"
    expose:
      - "3306"
